namespace Thio_Universal_Agent;

/// <summary>Optional per-request configuration overrides for AI provider calls.</summary>
public record AiRequestOptions(int? MaxOutputTokens = null);

/// <summary>Identifies the sender of a message in an AI conversation.</summary>
public enum AiChatRole
{
    /// <summary>A message sent by the user.</summary>
    User,

    /// <summary>A message generated by the AI model.</summary>
    Model,
}

/// <summary>Represents the result of an AI prompt call.</summary>
public record AiResponse(bool Success, string Text, string? ErrorMessage = null);

/// <summary>Represents a single message (turn) in an AI conversation.</summary>
public sealed class AiChatMessage
{
    /// <summary>The role of the sender (user or model).</summary>
    public required AiChatRole Role { get; init; }

    /// <summary>Optional text content of the message.</summary>
    public string? Text { get; init; }

    /// <summary>Optional image payload attached to the message.</summary>
    public byte[]? ImageBytes { get; init; }

    /// <summary>MIME type for <see cref="ImageBytes"/> (e.g. "image/png").</summary>
    public string? MimeType { get; init; }
}

/// <summary>
/// Tracks the ordered message history of a multi-turn AI conversation.
/// Pass an instance to <see cref="IAiProvider.ContinueConversationAsync(AiConversation, string, CancellationToken)"/>
/// (and its overloads) to continue an existing chat.
/// </summary>
public sealed class AiConversation
{
    private readonly List<AiChatMessage> _messages = [];

    /// <summary>The ordered messages exchanged so far.</summary>
    public IReadOnlyList<AiChatMessage> Messages => _messages;

    /// <summary>Appends a message to the conversation history.</summary>
    internal void AddMessage(AiChatMessage message) => _messages.Add(message);
}
